name: Template pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3

          - name: set uo docker buildx
            uses: docker/setup-buildx-action@v2

          - name: build docker image 
            run: |
              docker build -t api .

          - name: run docker container
            run: |
              docker run -d --name api -p 8000:8000 api

          - name: wait container for start
            run: |
              until curl --silent --fail http://localhost:8080; do
                echo "Waiting for container to start..."
              done
              echo "Container is ready"

          - name: stop and delete container
            run: |
              docker stop api
              docker rm api